spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/digitaldeck
    username: deckuser
    password: deckpass
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379